### ISSUE TITLE
Bug Report: Error occurs in the right text panel

### ISSUE THREAD

**Issue by Rerica0302** [dmMaze/BallonsTranslator#1256]
### Version Info

Python version:  3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
Python executable:  Ballonstranslator_win_minium\ballontrans_pylibs_win\python.exe
Version: 1.5.9
[INFO   ] logger:_enable_faulthandler:140 - Native crash traces enabled in log file: \Ballonstranslator_win_minium\logs\_2026_08_03-20_14_55.log
[INFO   ] network_mirrors:log_info:355 - Network mirror config already exists; skipping automatic mirror selection.
[INFO   ] launch:main:294 - QT_API: pyqt6, QT Version: 6.11.0
[INFO   ] launch:main:336 - set display language to ko_KR
[INFO   ] updater:_notify:401 - Updater: query_release https://github.com/dmMaze/BallonsTranslator/releases
[INFO   ] updater:_notify:401 - Updater: compare_versions 1.5.9 -> 1.5.9
[INFO   ] mainwindow:on_update_finished:626 - BallonsTranslator is already up-to-date: 1.5.9
[INFO   ] launch:warmup:144 - Grid transform acceleration is ready.

### Description of the Problem

https://github.com/user-attachments/assets/0fb7774b-a281-4371-9003-fed16e3a3add

**Describe the bug**
After updating from v1.5.9 to v1.5.9, individual text boxes in the right text list cannot be moved.
Additionally, when attempting to select multiple boxes by holding down the Shift key and clicking, the program crashes and outputs the following traceback log:

**Error Log**
```
Traceback (most recent call last):
  File "\Ballonstranslator_win_minium\ballontranslator\ui\text_engine\editing\widgets.py", line 888, in on_widget_checkstate_changed
    sel_min, sel_max = min(self.sel_anchor_widget.idx, tgt_w.idx), max(self.sel_anchor_widget.idx, tgt_w.idx)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'idx'
```

**To Reproduce**
1. Update BallonsTranslator to version 1.5.9.
2. Try to move text boxes in the right text panel. (They cannot be moved)
3. Hold Shift and click multiple text boxes to select them.
4. The application crashes instantly.

**Feature Request / Additional Context**
It would be great if users could select multiple text boxes using Shift or Ctrl keys and move them together.
Also, I'd love to request a feature that allows users to reorder the styles in Global Font Format by dragging and dropping.

**Affected Modules**
Some modules are missing or need updates:

* **Text Detector:** 
  * `ctbd`
* **OCR:** 
  * `google_vision`
  * `google_screen_ai_ocr`
  * `paddle_vl`
  * `PaddleOCRVLManga`
  * `ppv6_onnx`
* **Inpaint:** 
  * `flux2-klein`

### Text Detector

None

### OCR

None

### Inpaint

None

### Translator

None

### Logs

```shell

```

**Comment by dmMaze** [comment]
fixed in 1.5.10
